---
title: "Transcriptomics DE and GSEA analysis"
output: html_notebook
---


```{r}
require(DESeq2)
require(ggplot2)
require(UpSetR)
require(ComplexHeatmap)
require(circlize)
require(clusterProfiler)
require(ashr)
```
```{r}
cts = read.csv("counts_20221003.csv", row.names=1) #read.csv("deSeq2_counts.txt", sep = "\t", row.names = 1)
colnames(cts) = gsub("\\.", "_", colnames(cts))
colnames(cts) = gsub("clt_", "", colnames(cts))
colnames(cts) = gsub("_R1_bam", "", colnames(cts))
write.csv(cts, "counts_20221003_edited.csv")
head(cts)
```


```{r}
cts = cts[, colnames(cts) %in% c("Ramos_19O2_NoCyclo_1", "Ramos_19O2_NoCyclo_2", 
    "Ramos_19O2_NoCyclo_3", "Ramos_1O2_NoCyclo_1", "Ramos_1O2_NoCyclo_2", "Ramos_1O2_NoCyclo_3", 
    "Ramos_1O2_PlusCyclo_1", "Ramos_1O2_PlusCyclo_2", "Ramos_1O2_PlusCyclo_3")]
head(cts)
dim(cts)

```

```{r}
coldata = read.csv("transcriptomics_conditions_deseq.csv", row.names = 1, sep = ",")
coldata = coldata[colnames(cts), ]
coldata

```

```{r}
df = coldata
df = apply(df, FUN = function(x) gsub(",", "", x), MARGIN = c(1, 2))
df = apply(df, FUN = function(x) gsub("\\%", "percent", x), MARGIN = c(1, 2))
df = apply(df, FUN = function(x) gsub("\\-", "minus", x), MARGIN = c(1, 2))
df = apply(df, FUN = function(x) gsub("\\+", "plus", x), MARGIN = c(1, 2))
df = apply(df, FUN = function(x) gsub(" ", "\\.", x), MARGIN = c(1, 2))
colnames(df) = c("Condition", "O2", "CyA", "1percentO2.CyAminus", "19percentO2.CyAminus", 
    "1percentO2.CyAplus")
df

```

# Start DESeq2 analysis

```{r}
dds <- DESeqDataSetFromMatrix(countData = cts, colData = df, design = ~0 + Condition)
dds
```

```{r}
dds <- DESeq(dds, betaPrior = FALSE)
resultsNames(dds)  # lists the coefficients

```

## "19percent.O2.CyAminus" vs "1percent.O2.CyAminus"

```{r}
res <- results(dds, contrast = c("Condition", "19percent.O2.CyAminus", "1percent.O2.CyAminus"))
res <- as.data.frame(lfcShrink(dds, type = "ashr", res = res, contrast = c("Condition", 
    "19percent.O2.CyAminus", "1percent.O2.CyAminus")))
allRes = res
allRes$Contrast = '"19% O2, CyA- vs 1% O2 CyA-"'
res <- na.omit(res[res$padj < 0.05 & abs(res$log2FoldChange) > 0.5, ])
res
```
## "1percent.O2.CyAplus" vs "1percent.O2.CyAminus"

```{r}
res2 <- results(dds, contrast = c("Condition", "1percent.O2.CyAplus", "1percent.O2.CyAminus"))
# or to shrink log fold changes association with condition:
res2 <- as.data.frame(lfcShrink(dds, type = "ashr", res = res2, contrast = c("Condition", 
    "1percent.O2.CyAplus", "1percent.O2.CyAminus")))
res2$Contrast = '"1% O2, CyA+ vs 1% O2 CyA-"'
allRes = rbind(allRes, res2)
res2 <- na.omit(res2[res2$padj < 0.05 & abs(res2$log2FoldChange) > 0.5, ])
res2
```

## "1percent.O2.CyAplus" vs "19percent.O2.CyAminus"

```{r}
res3 <- results(dds, contrast = c("Condition", "1percent.O2.CyAplus", "19percent.O2.CyAminus"))
# or to shrink log fold changes association with condition:
res3 <- as.data.frame(lfcShrink(dds, type = "ashr", res = res3, contrast = c("Condition", 
    "1percent.O2.CyAplus", "19percent.O2.CyAminus")))
res3$Contrast = '"1% O2, CyA+ vs 19% O2 CyA-"'
allRes = rbind(allRes, res3)
write.csv(allRes,"DEseq_results.csv")
res3 <- na.omit(res3[res3$padj < 0.05 & abs(res3$log2FoldChange) > 0.5, ])
```


```{r}
listInput <- list(`1% O2, CyA+ vs 19% O2, CyA-` = rownames(res3), `19% O2, CyA- vs 1% O2, CyA-` = rownames(res), 
    `1% O2, CyA+ vs 1% O2, CyA-` = rownames(res2))
pdf(file = "upset_de_genes_transcriptomics.pdf")
upset(fromList(listInput), order.by = c("freq", "degree"), main.bar.color = "#3D9140", 
    matrix.color = "black", shade.color = "#E0EEE0", text.scale = 2)
dev.off()
png(file = "upset_de_genes_transcriptomics.png")
upset(fromList(listInput), order.by = c("freq", "degree"), main.bar.color = "#3D9140", 
    matrix.color = "black", shade.color = "#E0EEE0", text.scale = 2)
dev.off()

upset(fromList(listInput), order.by = c("freq", "degree"), main.bar.color = "#3D9140", 
    matrix.color = "black", shade.color = "#E0EEE0", text.scale = 2)
```


```{r}
DEheatmap = function(expMat, name = "", colGroups = NA, colIndicator = 1, cluster_columns = TRUE, 
    show_column_names = TRUE, ...) {
    require(ComplexHeatmap)
    require(circlize)
    if (!colIndicator) {
        ht = Heatmap(expMat, name = name, cluster_columns = TRUE, show_column_names = TRUE, 
            column_title = " ", col = colorRamp2(seq(min(expMat), max(expMat), length = 3), 
                c("blue", "white", "red")), use_raster = TRUE, raster_quality = 2, 
            raster_device = "png", ...)
        draw(ht)
    }
    if (colIndicator) {
        ht = Heatmap(expMat, name = name, cluster_columns = cluster_columns, top_annotation = colGroups, 
            show_column_names = show_column_names, column_title = " ", col = colorRamp2(seq(min(expMat), 
                max(expMat), length = 3), c("blue", "white", "red")), ...)
        draw(ht)
    }
}

```



```{r}
#rpmMat2 = read.csv("counts_20221003.csv") #read.csv("unfiltered_rpm_counts.txt", sep = "\t", row.names = 1)
#rpmMat2 = rpmMat2[, colnames(rpmMat2) %in% c("Ramos_19O2_NoCyclo_1", "Ramos_19O2_NoCyclo_2", 
#    "Ramos_19O2_NoCyclo_3", "Ramos_1O2_NoCyclo_1", "Ramos_1O2_NoCyclo_2", "Ramos_1O2_NoCyclo_3", 
#    "Ramos_1O2_PlusCyclo_1", "Ramos_1O2_PlusCyclo_2", "Ramos_1O2_PlusCyclo_3")]
#head(rpmMat2)
rpmMat2 = cts
```

## `19% O2, CyA- vs 1% O2, CyA-`

```{r}
heatmapData = rpmMat2[rownames(res), ]
type = trimws(gsub("O2", "% O2", gsub("PlusCyclo", "+ CyA", gsub("NoCyclo", "", gsub("Ramos_|_|_\\d+", 
    " ", colnames(heatmapData))))))
heatmapData = as.matrix(heatmapData)  #data.matrix(heatmapData)
heatmapData = apply(heatmapData, c(1, 2), as.numeric)
scaledHeatmap = as.matrix(t(scale(t(heatmapData))))
type = trimws(gsub("O2", "% O2", gsub("PlusCyclo", "+ CyA", gsub("NoCyclo", "", gsub("Ramos_|_|_\\d+", 
    " ", colnames(heatmapData))))))
ha = HeatmapAnnotation(type = type, border = TRUE, show_annotation_name = 0, which = "column", 
    annotation_legend_param = list(border = TRUE, title = "Treatment\n"), col = list(type = c(`19% O2` = "white", 
        `19% O2 + CyA` = "grey", `1% O2` = "black", `1% O2 + CyA` = "grey89")))
# png( 'unscaled_heatmap.png', width = 11, height = 11, units = 'in', res = 300 )
DEheatmap(scaledHeatmap, name = "Z-score\n", colGroups = ha, cluster_columns = TRUE, 
    show_column_names = FALSE, heatmap_legend_param = list(direction = "vertical"))
# dev.off()
```






```{r}
heatmapData = rpmMat2[rownames(res2), ]
type = trimws(gsub("O2", "% O2", gsub("PlusCyclo", "+ CyA", gsub("NoCyclo", "", gsub("Ramos_|_|_\\d+", 
    " ", colnames(heatmapData))))))
heatmapData = as.matrix(heatmapData)  #data.matrix(heatmapData)
heatmapData = apply(heatmapData, c(1, 2), as.numeric)
scaledHeatmap = as.matrix(t(scale(t(heatmapData))))
type = trimws(gsub("O2", "% O2", gsub("PlusCyclo", "+ CyA", gsub("NoCyclo", "", gsub("Ramos_|_|_\\d+", 
    " ", colnames(heatmapData))))))
ha = HeatmapAnnotation(type = type, border = TRUE, show_annotation_name = 0, which = "column", 
    annotation_legend_param = list(direction = "horizontal", border = TRUE, title = "Treatment\n"), 
    col = list(type = c(`19% O2` = "white", `19% O2 + CyA` = "grey", `1% O2` = "black", 
        `1% O2 + CyA` = "grey89")))
# png( 'unscaled_heatmap.png', width = 11, height = 11, units = 'in', res = 300 )
DEheatmap(scaledHeatmap, name = "Z-score\n", colGroups = ha, cluster_columns = TRUE, 
    show_column_names = FALSE)
# dev.off()
```






```{r}
heatmapData = rpmMat2[rownames(res3), ]
type = trimws(gsub("O2", "% O2", gsub("PlusCyclo", "+ CyA", gsub("NoCyclo", "", gsub("Ramos_|_|_\\d+", 
    " ", colnames(heatmapData))))))
heatmapData = as.matrix(heatmapData)  #data.matrix(heatmapData)
heatmapData = apply(heatmapData, c(1, 2), as.numeric)
scaledHeatmap = as.matrix(t(scale(t(heatmapData))))
type = trimws(gsub("O2", "% O2", gsub("PlusCyclo", "+ CyA", gsub("NoCyclo", "", gsub("Ramos_|_|_\\d+", 
    " ", colnames(heatmapData))))))
ha = HeatmapAnnotation(type = type, border = TRUE, show_annotation_name = 0, which = "column", 
    annotation_legend_param = list(direction = "horizontal", border = TRUE, title = "Treatment\n"), 
    col = list(type = c(`19% O2` = "white", `19% O2 + CyA` = "grey", `1% O2` = "black", 
        `1% O2 + CyA` = "grey89")))
#pdf('res3_scaled_heatmap.pdf', width = 9, height = 20)
DEheatmap(scaledHeatmap, name = "Z-score\n", colGroups = ha, cluster_columns = FALSE, 
    show_column_names = FALSE)
#dev.off()

```

```{r}
allDEgenes = unique(c(rownames(res), rownames(res2), rownames(res3)))
heatmapData = rpmMat2[allDEgenes,]
type = trimws(gsub("O2", "% O2", gsub(
    "PlusCyclo", "+ CyA", gsub("NoCyclo", "", gsub(
        "Ramos_|_|_\\d+",
        " ", colnames(heatmapData)
    ))
)))
heatmapData = as.matrix(heatmapData)
heatmapData = apply(heatmapData, c(1, 2), as.numeric)

pdf('allDEgenes_scaled_heatmap.pdf',
    width = 9,
    height = 20)
DEheatmap(
    scaledHeatmap,
    name = "Z-score\n",
    colGroups = ha,
    cluster_columns = TRUE,
    cluster_rows = TRUE,
    show_column_names = FALSE,
    column_km = 3,
    border = TRUE,
    row_km = 5
)
dev.off()
png(
    'allDEgenes_scaled_heatmap.png',
    width = 9,
    height = 20,
    units = "in",
    res = 300
)
DEheatmap(
    scaledHeatmap,
    name = "Z-score\n",
    colGroups = ha,
    cluster_columns = FALSE,
    cluster_rows = TRUE,
    show_column_names = FALSE,
    column_km = 3,
    border = TRUE,
    row_km = 5
)
dev.off()
DEheatmap(
    scaledHeatmap,
    name = "Z-score\n",
    colGroups = ha,
    cluster_columns = FALSE,
    cluster_rows = TRUE,
    show_column_names = FALSE,
    column_km = 3,
    border = TRUE,
    row_km = 5
)
```

# Horizontal DE genes heatmap

```{r}
allDEgenes = unique(c(rownames(res), rownames(res2), rownames(res3)))
heatmapData = rpmMat2[allDEgenes, ]
type = trimws(gsub("O2", "% O2", gsub("PlusCyclo", "+ CyA", gsub("NoCyclo", "", gsub("Ramos_|_|_\\d+", 
    " ", colnames(heatmapData))))))
heatmapData = as.matrix(heatmapData)
heatmapData = apply(heatmapData, c(1, 2), as.numeric)
ha = HeatmapAnnotation(type = type, border = TRUE, show_annotation_name = 0, which = "row", 
    annotation_legend_param = list(direction = "horizontal", border = TRUE, title = "Treatment\n"), 
    col = list(type = c(`19% O2` = "white", `19% O2 + CyA` = "grey", `1% O2` = "black", 
        `1% O2 + CyA` = "grey89")))
scaledHeatmap = t(as.matrix(t(scale(t(heatmapData)))))
ha = HeatmapAnnotation(
    type = type,
    border = TRUE,
    show_annotation_name = 0,
    which = "row",
    show_legend = TRUE,
    annotation_legend_param = list(
        direction = "horizontal", 'ncol' = 1,
        border = TRUE,
        title = "\nTreatment"
    , 'grid_height' = unit(0.25, 'in'), 'grid_width' = unit(0.5, 'in'), title_gp = gpar(fontsize = 20), title_position = 'leftcenter-rot', 'labels_gp' = gpar(fontsize=20)),
    col = list(
        type = c(
            `19% O[2]` = "white",
            #`19% O2 + CyA` = "grey",
            `1% O2` = "black",
            `1% O2 + CyA` = "darkgrey"
        )
    )
)


expMat = scaledHeatmap
ht = Heatmap(
    expMat,
    name = "\nZ-score (log2-RPM)",
    cluster_columns = TRUE,
    cluster_rows = TRUE,
    left_annotation = ha,
    right_annotation = ha,
    show_column_names = TRUE,
    show_row_names = FALSE,
    show_row_dend = FALSE,
    column_km=5,
    row_km=3,
    column_title = " ",
    heatmap_legend_param = list('direction' = 'vertical', 'legend_height' = unit(1, 'in'), 'grid_width' = unit(0.5, 'in'), title_gp = gpar(fontsize = 20), title_position = 'leftcenter-rot', 'labels_gp' = gpar(fontsize=20)),
    col = colorRamp2(seq(min(expMat),
                         max(expMat), length = 3), c("blue", "white", "red"))
)

pdf('allDEgenes_scaled_horizontal_heatmap.pdf', width = 22, height = 4)
draw(ht)
dev.off()
png('allDEgenes_scaled_horizontal_heatmap.png', width = 22, height = 4, units="in", res=600)
draw(ht)
dev.off()
draw(ht)
```

```{r}
keggGMT = read.gmt('c2.cp.kegg.v7.5.1.symbols.gmt')
resEnrich = as.data.frame(enricher(rownames(res), pvalueCutoff=1, TERM2GENE=keggGMT))
resEnrich$Contrast = "19% O2, CyA- vs 1% O2 CyA-"
allResEnrich = resEnrich
resEnrich = resEnrich[resEnrich$pvalue < 0.01,]
resEnrich
```

```{r}
resEnrich2 = as.data.frame(enricher(rownames(res2), pvalueCutoff=1, TERM2GENE=keggGMT))
resEnrich2$Contrast = "1% O2, CyA+ vs 1% O2 CyA-"
allResEnrich = rbind(allResEnrich, resEnrich2)
resEnrich2 = resEnrich2[resEnrich2$pvalue < 0.01,]
resEnrich2
```

```{r}
resEnrich3 = as.data.frame(enricher(rownames(res3), pvalueCutoff=1, TERM2GENE=keggGMT))
resEnrich3$Contrast = "1% O2, CyA+ vs 19% O2 CyA-"
allResEnrich = rbind(allResEnrich, resEnrich3)
resEnrich3 = resEnrich3[resEnrich3$pvalue < 0.01,]
resEnrich3
```

```{r}
write.csv(allResEnrich, "all_enrichment_results.csv")
allEnrich = allResEnrich[allResEnrich$pvalue < 0.01, ]
allEnrich$log10pvalue = (-1)*log10(allEnrich$pvalue)
allEnrich$ID = gsub("KEGG", "", allEnrich$ID)
allEnrich$ID = gsub("_", " ", allEnrich$ID)
allEnrich = allEnrich[order(allEnrich$Contrast, decreasing = FALSE),]
colnames(allEnrich)
```


```{r}
require(ggthemes)
allEnrich$Contrast = gsub(" vs ", "\nvs\n",allEnrich$Contrast)
enrichPlot = ggplot(data=allEnrich) + geom_point(size=4, aes(x = log10pvalue, y = reorder(ID, -log10pvalue))) + facet_wrap(vars(Contrast), as.table=TRUE, nrow=1) + theme_pander(nomargin = TRUE, fc = "black", gM=TRUE, gm=TRUE, gc = "black", boxes=TRUE, gl = "dotdash") + xlab("-log10 (p-value)") + ylab("")+ theme(strip.background = element_rect(fill = "cornsilk"), strip.placement = "outside", text=element_text(size=30))
enrichPlot
ggsave(filename = "all_enrichr_results.pdf", plot = enrichPlot, width = 10, height=3)
ggsave(filename = "all_enrichr_results.png", plot = enrichPlot, width = 10, height=3)
```


```{r}
upset = upset(fromList(listInput), order.by = c("freq", "degree"), main.bar.color = "#3D9140", 
    matrix.color = "black", shade.color = "#E0EEE0", text.scale = 2)
#upset
#plot(enrichPlot)
#draw(ht)
ggpubr::ggarrange(upset, enrichPlot, ht, ncol = 1)
```


















