---
title: "Application of MOFA - Model training and GSEA"
output: html_notebook
---

Model training (follows tutorial https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/getting_started_R.html)

```{r, eval=FALSE}
require(data.table)
require(MOFA2)
require(purrr)
require(ggplot2)
require(cowplot)
require(MOFAdata)
```
Load data

```{r, eval=FALSE}
data <- make_example_data(
  n_views = 3, 
  n_samples = 15, 
  n_features = 1000, 
  n_factors = 10
)[[1]]
MOFAobject <- create_mofa(data)
```

```{r, eval=FALSE}
#transcriptomics = read.csv("bonita_transcriptomics.csv", row.names=1)
#proteomics = read.csv("bonita_proteomics.csv", row.names=1)
#phosphoproteomics = read.csv("bonita_phosphoproteomics.csv", row.names=1)
concatenated = read.csv("concatenated_datasets.csv", row.names = 1)
head(concatenated)
conditions = read.csv("concatenated_conditions.csv")
head(conditions)
```

```{r}
require(reshape2)
```

```{r}
cv = function(x){
  return(sd(x)/mean(x))
}
```

```{r}
transcriptomics = read.csv("bonita_transcriptomics.csv")
proteomics = read.csv("bonita_proteomics.csv")
phosphoproteomics = read.csv("bonita_phosphoproteomics.csv")
```

```{r}
cvRows = apply(transcriptomics[1:nrow(transcriptomics),2:ncol(transcriptomics)],  1, cv)
hist(cvRows)
threshold = mean(cvRows)
hvgsTrans = transcriptomics[cvRows>2*threshold,]
dim(hvgsTrans)
```

```{r}
cvRows = apply(proteomics[1:nrow(proteomics),2:ncol(proteomics)],  1, cv)
hist(cvRows)
threshold = mean(cvRows)
hvgsProt = proteomics[cvRows>2*threshold,]
dim(hvgsProt)
```


```{r}
cvRows = apply(phosphoproteomics[1:nrow(phosphoproteomics),2:ncol(phosphoproteomics)],  1, cv)
hist(cvRows)
threshold = mean(cvRows)
hvgsPhosph = phosphoproteomics[cvRows>2*threshold,]
dim(hvgsPhosph)
```

```{r}
transMelt = melt(hvgsTrans, id.vars = 'X')
transMelt$View = "Transcriptomics"
head(transMelt)
protMelt = melt(hvgsProt, id.vars = 'X')
protMelt$View = "Proteomics"
head(protMelt)
phosphMelt = melt(hvgsPhosph, id.vars = 'X')
phosphMelt$View = "Phosphoproteomics"
head(phosphMelt)
concatMelt = rbind(transMelt, protMelt, phosphMelt)
colnames(concatMelt) = c("feature", "sample", "value", "view")
concatMelt$sample = make.names(concatMelt$sample)
head(concatMelt)
```
```{r}
conditions = read.csv("concatenated_conditions_MOFA.csv")
conditions$variable = make.names(conditions$variable)
head(conditions)
conditions$sample = conditions$variable 
#conditions$SampleName = unlist(lapply(1:length(conditions$variable), function(i){paste0(conditions$Condition[i], "_", make.names(conditions$Dataset[i]),"_", conditions$SampleNumber[i])}))
```

```{r}
levels(concatMelt$sample)[!make.names(levels(concatMelt$sample)) %in% make.names(conditions$variable)]
```


```{r}
concatMelt$sample = unlist(lapply(concatMelt$sample, function(x){conditions$SampleName[conditions$variable == x]}))
#concatMelt$sample = make.unique(concatMelt$sample)
concatMelt$feature = unlist(lapply(1:length(concatMelt$feature), function(i){paste0(concatMelt$feature[i], "_", concatMelt$view[i])})) 
concatMelt$group = "group_0"
#concatMelt = concatMelt[!duplicated(concatMelt[,c("feature","sample","view","group")]),] # remove duplicates
```

```{r}
concatMelt$sample = make.names(concatMelt$sample)
write.csv(concatMelt, "concatMelt.csv")
unique(concatMelt$sample)
```

```{r,eval=FALSE}
require(MOFA2)
MOFAobject <- create_mofa(concatMelt)
```

```{r,eval=FALSE}
plot_data_overview(MOFAobject)
```


```{r,eval=FALSE}
MOFAobject <- prepare_mofa(
  object = MOFAobject)
```


```{r,eval=FALSE}

outfile = file.path(getwd(),"model.hdf5")
MOFAobject.trained <- run_mofa(MOFAobject, outfile)
```

```{r}
require(MOFA2)
model <- load_model("model.hdf5")
```
```{r}
plot_data_overview(model)
```

```{r}

```

```{r}
model@cache[["variance_explained"]]
plot_variance_explained(model)
```
```{r}
plot_data_heatmap(model,
  view = "Transcriptomics",         # view of interest
  factor = 1,             # factor of interest
  features = 20,          # number of features to plot (they are selected by weight)
  
  # extra arguments that are passed to the `pheatmap` function
  cluster_rows = TRUE, cluster_cols = TRUE,
  show_rownames = TRUE, show_colnames = TRUE
)
```

```{r}
plot_data_heatmap(model,
  view = "Proteomics",         # view of interest
  factor = 1,             # factor of interest
  features = 20,          # number of features to plot (they are selected by weight)
  
  # extra arguments that are passed to the `pheatmap` function
  cluster_rows = TRUE, cluster_cols = TRUE,
  show_rownames = TRUE, show_colnames = TRUE
)
```

```{r}
plot_data_heatmap(model,
  view = "Phosphoproteomics",         # view of interest
  factor = 1,             # factor of interest
  features = 20,          # number of features to plot (they are selected by weight)
  
  # extra arguments that are passed to the `pheatmap` function
  cluster_rows = TRUE, cluster_cols = TRUE,
  show_rownames = TRUE, show_colnames = TRUE
)
```

```{r}
sample_metadata = conditions[,c("SampleName","Condition")]
sample_metadata$sample = make.names(sample_metadata$SampleName)
sample_metadata = sample_metadata[!duplicated(sample_metadata),]
samples_metadata(model) <- sample_metadata
```

```{r}
plot_dimred(model,
  method = "TSNE",  # method can be either "TSNE" or "UMAP"
  color_by = "Condition",
  perplexity = 1, dot_size = 5, label=TRUE
)
```

```{r}
require(MOFAdata)
data("MSigDB_v6.0_C5_human") 
MSigDB_v6.0_C5_human[1:5,1:5]
```

```{r}
require(clusterprofiler)
```


```{r}
enrichment.parametric <- run_enrichment(model,
  view = "Transcriptomics", factors = 1:3,
  feature.sets = MSigDB_v6.0_C5_human,
  sign = "negative",
  statistical.test = "parametric"
)
```

```{r}

```































































