---
title: "Compare CAMERA + some pvalue combination method, leapR, paintomics, mBONITA, multiGSEA"
output: html_notebook
---

```{r}
require(ComplexHeatmap)
require(ggplot2)
require(ggplotify)
require(stringr)
require(UpSetR)
require(ggsci)
require(ggpubr)
require(gridExtra)
```

# Load data

```{r}

threshold <- 0.05
cwd <- getwd()
methods <- c("CAMERA", "LeapR", "PaintOmics", "ActivePathways", "mBONITA", "multiGSEA")#"BONITA", 
PAlist <- vector(mode = "list", length = length(methods))
names(PAlist) <- methods
PAlist[["CAMERA"]] <- read.csv(paste0(cwd, "/reactomeGSA-camera/camera_combinedPvalues.csv"), row.names = 1)
temp <- PAlist[["CAMERA"]]$FDR < threshold #PValue < 0.01
PAlist[["CAMERA"]] <- na.omit(PAlist[["CAMERA"]][temp,])

PAlist[["LeapR"]] <- read.csv(paste0(cwd, "/leapR/leapR_allResults.csv"))
temp <- PAlist[["LeapR"]]$BH_pvalue < threshold
PAlist[["LeapR"]] <- na.omit(PAlist[["LeapR"]][temp,])
PAlist[["LeapR"]]$Pathway <- trimws(gsub("KEGG|_|\\d+$", " ", PAlist[["LeapR"]]$Pathway))

PAlist[["PaintOmics"]]<- as.data.frame(read.csv(paste0(cwd, "/paintomics/paintomics_allResults.csv"), row.names = 1))
colnames(PAlist[["PaintOmics"]])[1] <- "Pathway"
temp <- PAlist[["PaintOmics"]]$CombinedFDR_BH < threshold
PAlist[["PaintOmics"]] <- PAlist[["PaintOmics"]][temp,]
PAlist[["PaintOmics"]]$Method <- "Combined"
PAlist[["PaintOmics"]]$negativelog10FDR <- (-1)*log10(PAlist[["PaintOmics"]]$CombinedFDR_BH)

PAlist[["ActivePathways"]]<- read.csv(paste0(cwd, "/ActivePathways/activePathways_allResults.csv"), row.names = NULL)
temp <- PAlist[["ActivePathways"]]$adjusted.p.val < threshold
PAlist[["ActivePathways"]] <- PAlist[["ActivePathways"]][temp,]


#PAlist[["BONITA"]]<- read.csv(paste0(cwd, "/mBonita_pvalues/Bonita_allResults.csv"), row.names = 1)
#temp <- PAlist[["BONITA"]]$FDR < threshold
#PAlist[["BONITA"]] <- na.omit(PAlist[["BONITA"]][temp,])
#PAlist[['BONITA']] <- na.omit(PAlist[["BONITA"]][PAlist[["BONITA"]]$Method %in% c('Combined'),])
##levels(PAlist$BONITA$Contrast) <- c("X19O2NoCyA - X1O2PlusCyA", "X19O2NoCyA - X1O2NoCyA", "X1O2PlusCyA - X1O2NoCyA" )


PAlist[["mBONITA"]]<- read.csv(paste0(cwd, "/mBonita_pvalues/mBonita_pvalues.csv"), row.names = 1)
temp <- PAlist[["mBONITA"]]$BHpvals < threshold
PAlist[['mBONITA']]$Algorithm <- 'mBONITA'
PAlist[['mBONITA']]$Method <- 'Concatenated'
PAlist[["mBONITA"]] <- na.omit(PAlist[["mBONITA"]][temp,])
PAlist[["mBONITA"]]$Pathway.Code <- PAlist[["mBONITA"]]$Pathway 
PAlist[["mBONITA"]]$Pathway <- PAlist[["mBONITA"]]$Pathway.Name
PAlist[["mBONITA"]]$negativelog10FDR <- PAlist[["mBONITA"]]$negativeLog10_adjpvals

PAlist[["multiGSEA"]]<- read.csv(paste0(cwd, "/multiGSEA/multiGSEA_allResults.csv"), row.names = 1)
PAlist[["multiGSEA"]]<- na.omit(PAlist[["multiGSEA"]][PAlist[["multiGSEA"]]$combined_padj < threshold,])
PAlist[["multiGSEA"]]$Method <- "Combined"

for (n in names(PAlist)){
  print(n)
  PAlist[[n]]$Contrast <- gsub('X1O2NoCyA - X19O2NoCyA', '1% O2, CyA- vs 19% O2, CyA-', PAlist[[n]]$Contrast)
  PAlist[[n]]$Contrast <- gsub('X1O2PlusCyA - X1O2NoCyA', '1% O2, CyA+ vs 1% O2, CyA-', PAlist[[n]]$Contrast)
  PAlist[[n]]$Contrast <- gsub('X19O2NoCyA - X1O2PlusCyA', '19% O2, CyA- vs 1% O2, CyA+', PAlist[[n]]$Contrast)
  PAlist[[n]]$Contrast <- gsub("X19O2NoCyA - X1O2NoCyA", '1% O2, CyA- vs 19% O2, CyA-', PAlist[[n]]$Contrast)
  PAlist[[n]]$Contrast <- gsub("X1O2NoCyA - X1O2PlusCyA", '1% O2, CyA+ vs 1% O2, CyA-', PAlist[[n]]$Contrast)
  PAlist[[n]]$Contrast <- gsub("X1O2NoCyA vs X19O2NoCyA", '1% O2, CyA- vs 19% O2, CyA-', PAlist[[n]]$Contrast)
  PAlist[[n]]$Contrast <- gsub("X1O2PlusCyA - X19O2NoCyA", '19% O2, CyA- vs 1% O2, CyA+', PAlist[[n]]$Contrast)
  print(unique(PAlist[[n]]$Contrast))
}


#PAlist[[""]]<- read.csv(paste0(cwd, ""))

print(lapply(PAlist, dim))
```
# Pathways only identified by mBONITA
No longer valid after new metric
```{r, eval=FALSE}
temp <- PAlist[['mBONITA']]
tempPath <- setdiff(temp$Pathway, Reduce(union, list(PAlist[["CAMERA"]]$Pathway, PAlist[["LeapR"]]$Pathway, PAlist[["PaintOmics"]]$Pathway, PAlist[["ActivePathways"]]$Pathway)))
unique_mb <- na.omit(temp[temp$Pathway %in% tempPath,])
unique_mb <- na.omit(unique_mb[unique_mb$negativelog10FDR > (-1)*log10(0.05),])
ggplot(unique_mb) + geom_point(aes(x=negativelog10FDR, y=Pathway, color=Contrast)) + facet_wrap(facets = 'Contrast', drop=TRUE) + theme_pubr() + theme(panel.grid.major = element_line("gray",0.5), panel.grid.minor = element_line("gray",0.25))
ggsave(filename = "mBonita_uniqueResults_allMethods.svg", width = 10, height = 24, units = 'in')
ggsave(filename = 'mBonita_uniqueResults_allMethods.png', width = 10, height = 24, units = 'in')
```


# UpSet plot

```{r}


makeVisList <- function(tempPAlist, contrast) {
  visList <- tempPAlist
  tempPAlist <-
    lapply(tempPAlist, function(x) {
      return(x[x$Contrast == contrast, ])
    })
  visList[["CAMERA"]] <-
    unique(str_to_title(trimws(as.vector(tempPAlist[["CAMERA"]]$Pathway[tempPAlist[["CAMERA"]]$Method == "Combined"]))))
  visList[["LeapR"]] <-
    unique(str_to_title(as.vector(tempPAlist[["LeapR"]]$Pathway[tempPAlist[["LeapR"]]$Method == "Phosphoproteomics"]))) #NO COMBINED RESULTS YET
  visList[["PaintOmics"]] <-
    unique(str_to_title(trimws(as.vector(
      tempPAlist[["PaintOmics"]]$Pathway
    )))) #ALREADY FILTERED TO COMBINED PVALS IN PREVIOUS STEP
  visList[["BONITA"]] <-
     unique(str_to_title(trimws(as.vector(tempPAlist[["BONITA"]]$Pathway[tempPAlist[["BONITA"]]$Method == "Combined"]))))
  visList[["mBONITA"]] <-
    unique(str_to_title(trimws(as.vector(tempPAlist[["mBONITA"]]$Pathway[tempPAlist[["mBONITA"]]$Algorithm == "mBONITA"]))))
  visList[["ActivePathways"]] <-
    unique(str_to_title(trimws(as.vector(
      tempPAlist[["ActivePathways"]]$Pathway
    ))))
  visList[["multiGSEA"]] <- unique(str_to_title(trimws(as.vector(
      tempPAlist[["multiGSEA"]]$Pathway
    ))))
  visList <- lapply(visList, function(x){if(length(x) > 0){return(x)}else{return(NA)}})
  visList <- visList[!is.na(visList)]
  #print(visList)
  return(visList)
}

```

# Combined plot


```{r}

# "1% O2, CyA- vs 19% O2, CyA-" "1% O2, CyA+ vs 1% O2, CyA-"  "19% O2, CyA- vs 1% O2, CyA+"
visList <- makeVisList(PAlist, "19% O2, CyA- vs 1% O2, CyA+")
png(filename = "upset_X19O2NoCyA - X1O2PlusCyA.png", width = 4.5, height = 3.5, pointsize = 16, res = 1200, units = 'in')
upset(fromList(visList), order.by = c("freq", "degree"), mb.ratio = c(0.45, 0.55), empty.intersections = NULL, point.size = 4, line.size = 1 , mainbar.y.label = "Intersections", sets.x.label = "Pathways", text.scale = c(1.5,1.5,1.5,1.5,2,2), number.angles = 0, main.bar.color = 'black', sets.bar.color = 'black', shade.color = 'white', matrix.color = 'black')
dev.off()

svg(filename = "upset_X19O2NoCyA - X1O2PlusCyA.svg", width = 4.5, height = 3.5, pointsize = 16)
upset(fromList(visList), order.by = c("freq", "degree"), mb.ratio = c(0.45, 0.55), empty.intersections = NULL, point.size = 4, line.size = 1 , mainbar.y.label = "Intersections", sets.x.label = "Pathways", text.scale = c(1.5,1.5,1.5,1.5,2,2), number.angles = 0, main.bar.color = 'black', sets.bar.color = 'black', shade.color = 'white', matrix.color = 'black')
dev.off()

#upset1 = upset(fromList(visList), order.by = c("freq", "degree"), mb.ratio = c(0.6,0.4), empty.intersections = NULL, point.size = 4, line.size = 1 , mainbar.y.label = "Intersections", sets.x.label = "Pathways", text.scale = c(1.5,1.5,1.5,1.5,2,1.75), number.angles = 0, main.bar.color = 'black', sets.bar.color = 'black', shade.color = 'white', matrix.color = 'black')

lt = make_comb_mat(list_to_matrix(visList))
upset1 = UpSet(lt, pt_size = unit(5, "mm"), right_annotation = upset_right_annotation(lt, add_numbers = TRUE, numbers_rot = 0,numbers_gp = gpar(cex=1)),  top_annotation = upset_top_annotation(lt, add_numbers = TRUE, numbers_rot = 0,numbers_gp = gpar(cex=1)))
upset1 = as.grob(upset1)
```

```{r}
# "1% O2, CyA- vs 19% O2, CyA-" "1% O2, CyA+ vs 1% O2, CyA-"  "19% O2, CyA- vs 1% O2, CyA+"
visList <- makeVisList(PAlist, "1% O2, CyA- vs 19% O2, CyA-")
png(filename = "upset_X19O2NoCyA - X1O2NoCyA.png", width = 4.5, height = 3.5, pointsize = 16, res = 1200, units = 'in')
upset(fromList(visList), order.by = c("freq", "degree"), mb.ratio = c(0.55, 0.45), empty.intersections = NULL, point.size = 4, line.size = 1 , mainbar.y.label = "Intersections", sets.x.label = "Pathways", text.scale = c(1.5,1.5,1.5,1.5,1.5,1.5), number.angles = 0, main.bar.color = 'black', sets.bar.color = 'black', shade.color = 'white', matrix.color = 'black')
dev.off()

svg(filename = "upset_X19O2NoCyA - X1O2NoCyA.svg", width = 4.5, height = 3.5, pointsize = 16)
upset(fromList(visList), order.by = c("freq", "degree"), mb.ratio = c(0.55, 0.45), empty.intersections = NULL, point.size = 4, line.size = 1 , mainbar.y.label = "Intersections", sets.x.label = "Pathways", text.scale = c(1.5,1.5,1.5,1.5,1.5,1.5), number.angles = 0, main.bar.color = 'black', sets.bar.color = 'black', shade.color = 'white', matrix.color = 'black')
dev.off()

#upset2 = upset(fromList(visList), order.by = c("freq", "degree"), mb.ratio = c(0.6,0.4), empty.intersections = NULL, point.size = 4, line.size = 1 , mainbar.y.label = "Intersections", sets.x.label = "Pathways", text.scale = c(1.5,1.5,1.5,1.5,2,1.75), number.angles = 0, main.bar.color = 'black', sets.bar.color = 'black', shade.color = 'white', matrix.color = 'black')
#complexheatmap version
lt = make_comb_mat(list_to_matrix(visList))
upset2 = UpSet(lt, pt_size = unit(5, "mm"), right_annotation = upset_right_annotation(lt, add_numbers = TRUE, numbers_rot = 0,numbers_gp = gpar(cex=1)),  top_annotation = upset_top_annotation(lt, add_numbers = TRUE, numbers_rot = 0,numbers_gp = gpar(cex=1)))
upset2 = as.grob(upset2)
```

```{r}
# "1% O2, CyA- vs 19% O2, CyA-" "1% O2, CyA+ vs 1% O2, CyA-"  "19% O2, CyA- vs 1% O2, CyA+"
visList <- makeVisList(PAlist, "1% O2, CyA+ vs 1% O2, CyA-")
png(filename = "upset_X1O2PlusCyA - X1O2NoCyA.png", width = 4.5, height = 3.5, pointsize = 16, res = 1200, units = 'in')
upset(fromList(visList), order.by = c("freq", "degree"), mb.ratio = c(0.55, 0.45), empty.intersections = NULL, point.size = 4, line.size = 1 , mainbar.y.label = "Intersections", sets.x.label = "Pathways", text.scale = c(1.5,1.5,1.5,1.5,1.5,1.5), number.angles = 0, main.bar.color = 'black', sets.bar.color = 'black', shade.color = 'white', matrix.color = 'black')
dev.off()

svg(filename = "upset_X1O2PlusCyA - X1O2NoCyA.svg", width = 4.5, height = 3.5, pointsize = 16,)
upset(fromList(visList), order.by = c("freq", "degree"), mb.ratio = c(0.55, 0.45), empty.intersections = NULL, point.size = 4, line.size = 1 , mainbar.y.label = "Intersections", sets.x.label = "Pathways", text.scale = c(1.5,1.5,1.5,1.5,1.5,1.5), number.angles = 0, main.bar.color = 'black', sets.bar.color = 'black', shade.color = 'white', matrix.color = 'black')
dev.off()

#upset3 = upset(fromList(visList), order.by = c("freq", "degree"), mb.ratio = c(0.6,0.4), empty.intersections = NULL, point.size = 4, line.size = 1 , mainbar.y.label = "Intersections", sets.x.label = "Pathways", text.scale = c(1.5,1.5,1.5,1.5,2,1.75), number.angles = 0, main.bar.color = 'black', sets.bar.color = 'black', shade.color = 'white', matrix.color = 'black')
lt = make_comb_mat(list_to_matrix(visList))
upset3 = UpSet(lt, pt_size = unit(5, "mm"), right_annotation = upset_right_annotation(lt, add_numbers = TRUE, numbers_rot = 0,numbers_gp = gpar(cex=1)),  top_annotation = upset_top_annotation(lt, add_numbers = TRUE, numbers_rot = 0,numbers_gp = gpar(cex=1)))
upset3 = as.grob(upset3)
```
# Are the pathways of interest significant?

```{r}
pathways <- as.vector(read.table("PATHWAYS IN HIF1A NETWORK KEGG IDS.txt", header=FALSE, fill=TRUE)[,1])
print(pathways)
```

```{r}
gmt <- read.table('kegg_networks_edited.gmt', header=FALSE, fill=TRUE, sep = "\t")[,1:2]
colnames(gmt) <- c('Pathway', 'KEGGID')
gmt <- na.omit(gmt[gmt$KEGGID %in% pathways, c("KEGGID", "Pathway")])
rownames(gmt) <- gmt$KEGGID
print(gmt)
```

```{r}
PAlist2 <- lapply(PAlist, function(x){return(x[x$Method %in% c("Concatenated", "Combined", "mBONITA"), intersect(colnames(x), c('Contrast', 'Pathway',"Method", 'negativelog10FDR'))])}) #lapply(PAlist, function(x){return(x[x$Pathway %in% gmt$Pathway & x$Method %in% c("Concatenated", "Combined"), intersect(colnames(x), c('Contrast', 'Pathway',"Method", 'negativelog10FDR'))])})
PAlist2$Pathway <- unlist(lapply(PAlist2$Pathway, function(x){if(x %in% gmt$Pathway){return(paste0(x, "**"))}}))
PAlist2 <- Filter(function(x) dim(x)[1] > 0, PAlist2)
for (i in names(PAlist2)){
  PAlist2[[i]]$Algorithm <- i
  print(i)
  print(colnames(PAlist2[[i]]))
  print("###")
}

PAlist2 <- do.call(rbind,PAlist2)
rownames(PAlist2) <- 1:nrow(PAlist2)
PAlist2$Method <- 'Combined'
PAlist2
```

```{r, eval=TRUE}
PAlist2 <- reshape2::acast(PAlist2, Pathway ~ Algorithm ~ Contrast, value.var = 'negativelog10FDR')
PAlist2[is.na(PAlist2)] <- 0
PAlist2 <- reshape2::melt(PAlist2)
colnames(PAlist2) <- c("Pathway", "Algorithm", "Contrast", "negativelog10FDR")
PAlist2
```

```{r, eval=FALSE}
temp <- reshape2::melt(PAlist2[,,'X19O2NoCyA - X1O2NoCyA'])
colnames(temp) <- c("Pathway", "Algorithm", "negativelog10FDR")
  
ggplot(temp, aes(Algorithm, Pathway, fill=negativelog10FDR)) +
  geom_tile() + scale_fill_gradient(low="white", high="blue")
```


```{r}

PAlist2$Significant <- as.factor(unlist(lapply(PAlist2$negativelog10FDR, function(x){if(x<1.303){return(FALSE)}else{return(TRUE)}})))

#filter out pathways that aren't significant in any method/contrast combination
#aggregate(Significant ~ Pathway, data = PAlist2, FUN = sum)

p1 <- ggplot(PAlist2, aes(Algorithm, Pathway, fill=Significant)) + geom_tile(color = 'black', size = 0.3) + facet_wrap(~Contrast) + theme_pubr() + rotate_x_text(90) + scale_fill_brewer()
#ggpar(p1, palette = "npg")
#png(filename = "heatmap_HIF1pathways.png", width = 10, height = 4, pointsize = 14, res = 600, units = 'in')
png(filename = "heatmap_allKEGGpathways.png", width = 20, height = 14, pointsize = 14, res = 600, units = 'in')
p1 
dev.off()
print(p1)

svg(filename = "heatmap_allKEGGpathways.svg", width = 10, height = 14, pointsize = 14)
p1 
dev.off()
print(p1)
```



```{r}
PAlist2$Pathway <- gsub("\\*\\*", "", PAlist2$Pathway)
PAlist2 <- na.omit(PAlist2[PAlist2$Pathway %in% gmt$Pathway,])
PAlist2$Contrast <- gsub(" vs ", "\nvs ", PAlist2$Contrast)
PAlist2$Pathway <- gsub(" pathway", "", PAlist2$Pathway)
p1 <- ggplot(PAlist2, aes(Algorithm, Pathway, fill=Significant)) + geom_tile(color = 'black', size = 0.3) + facet_wrap(~Contrast) + theme_pubr() + rotate_x_text(90) + scale_fill_brewer() + theme(text = element_text(size=16))
#ggpar(p1, palette = "npg")
#png(filename = "heatmap_HIF1pathways.png", width = 10, height = 4, pointsize = 14, res = 600, units = 'in')
png(filename = "heatmap_HIF1_pathways.png", width = 10, height = 10, pointsize = 14, res = 600, units = 'in')
p1 
dev.off()
print(p1)

svg(filename = "heatmap_HIF1_pathways.svg", width = 10, height = 10, pointsize = 14)
p1 
dev.off()
print(p1)

hif1 = p1
```

```{r}

PAlist2 <- as.data.frame(apply(PAlist2, 2, as.vector))
signif_in_most_methods <- unique(PAlist2$Pathway[PAlist2$Significant == TRUE & PAlist2$Algorithm %in% c("ActivePathways", "CAMERA", "mBONITA", "PaintOmics", "multiGSEA")])

PAlist2$Pathway <- gsub("\\*\\*", "", PAlist2$Pathway)
PAlist2 <- na.omit(PAlist2[PAlist2$Pathway %in% signif_in_most_methods,])

p1 <- ggplot(PAlist2, aes(Algorithm, Pathway, fill=Significant)) + geom_tile(color = 'black', size = 0.3) + facet_wrap(~Contrast) + theme_pubr() + rotate_x_text(90) + scale_fill_brewer()
#ggpar(p1, palette = "npg")
#png(filename = "heatmap_HIF1pathways.png", width = 10, height = 4, pointsize = 14, res = 600, units = 'in')
png(filename = "heatmap_signif_in_most_methods.png", width = 10, height = 10, pointsize = 14, res = 600, units = 'in')
p1 
dev.off()
print(p1)

svg(filename = "heatmap_signif_in_most_methods.svg", width = 10, height = 10, pointsize = 14)
p1 
dev.off()
print(p1)
```
```{r}
upset1 = as.grob(upset1)
upset2 = as.grob(upset2)
upset3 = as.grob(upset3)


svg('Figure5_autoArranged.svg', width = 11, height = 10)
ggarrange(ggarrange(upset2,upset3,upset1,labels = c("A", "B", "C"), nrow=1, ncol = 3), hif1, labels = c("", "D"), nrow = 2, heights = c(1.25,1.5))
dev.off()

pdf('Figure5_autoArranged.pdf', width = 11, height = 10)
ggarrange(ggarrange(upset2,upset3,upset1,labels = c("A", "B", "C"), nrow=1, ncol = 3), hif1, labels = c("", "D"), nrow = 2, heights = c(1.25,1.5)) 
dev.off()
#p5 = arrangeGrob(upset2,upset3,upset1,hif1, layout_matrix = matrix(data = c(1,2,3,1,2,3,4,4,4,4,4,4,4,4,4), ncol=3, nrow=5, byrow=TRUE)) #note order
#ggsave('temp2.svg', p5, height = 10, width = 10, units="in")
```

